package:
  name: queryfuse
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0') }}
source:
  # or from git:
  git_url: https://github.com/yuxiangtan/QueryFuse.git
  # once we have a release, uncomment next line and change it to match
  # release tag name
  #git_tag: v1

build:

  number: 0       # (defaults to 0)

requirements:

  run:
   - samtools	
   - bedtools
   - bamtools
   - python
   - boost <=1.51
   - bowtie
   - bowtie2
   - r
   - perl
   - pysam

test:
  commands:
    - QF_wrapper -h

about:
  home: https://github.com/yuxiangtan/QueryFuse
  license: Apache Version 2.0
